name: Generate and Deploy Calvin and Hobbes Feed

on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 11 * * *'
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  # Job 1: Genereert het .xml bestand
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Gebruik een specifieke versie voor consistentie
          python-version: '3.11'
      
      # DEZE STAP IS VERWIJDERD
      # - name: Set up Chrome
      #   uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Gebruik requirements.txt als 'single source of truth'
          pip install -r requirements.txt

      - name: Run Python script to generate feed
        run: python generate_calvinandhobbes.py

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Optioneel: Wees specifiek over welk bestand je uploadt
          path: './calvinandhobbes.xml'

  # Job 2: Publiceert het gegenereerde bestand
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4